#Asignment-1 Workflow

name: pull request check workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 pr-check:
   runs-on: ubuntu-latest
  
   steps:
    - name: checkout repository
      uses: actions/checkout@v1
    #Set up JDK 11
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
    #Set up Maven cache
    - name: Build with Maven
      run: |
        mvn -B package --file WebApp/pom.xml
        mkdir target && cp WebApp/target/*.jar target
   #Run Tests
   #- name: Run Tests
   #  run: mvn -B test
    # Validate Packer
    - name: Validate AMI Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: WebApp/packer/ami.json
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    # Init Packer
   # - name: Initialize AMI Packer Template
    #  uses: hashicorp/packer-github-actions@master
     # with:
     #   command: init
      #  target: WebApp/packer/ami.json
    # Build Packer
    - name: Build Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort"
        target: WebApp/packer/ami.json
      env:
        PACKER_LOG: 1
        GITHUB_REPO_PATH: ${{ github.workspace }}
